### ISSUE TITLE
Delegate say method to character

### ISSUE THREAD

**Issue by yogaraptor** [pjhauser/odysseus#13]
People talk, scenes don't. Suggest `Character#say` fires an event on the character, e.g. `speak`. `Narrative` listens for these events and renders them. Might seem circuitous initially, as `Character#say` will be called by `Narrative#go`, but it adds potential for characters to speak autonomously in response to other events (e.g Samwise lets out an involuntary moan when the Lembas Bread resource falls below 2)

**Comment by zweck** [comment]
Added in 73fa51b95b347f2c5984a5b8bc610ba60958d329
